#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FilmScout.Resource", IsApplication=true)]

namespace FilmScout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int gen_arrays = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int you = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07003f
			public const int DAdd = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int DB1 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int DB2 = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int DB3 = 2131165250;
			
			// aapt resource value: 0x7f07003e
			public const int Dir = 2131165246;
			
			// aapt resource value: 0x7f070034
			public const int EYS = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int EndY = 2131165235;
			
			// aapt resource value: 0x7f070047
			public const int FMM = 2131165255;
			
			// aapt resource value: 0x7f07000b
			public const int HomeB = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int LButt = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int LEmail = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int LPass = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int LoginB = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Movie = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int Names = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int REmail = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int RFName = 2131165205;
			
			// aapt resource value: 0x7f070017
			public const int RLName = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int RName = 2131165201;
			
			// aapt resource value: 0x7f07001a
			public const int RPass = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int RPass2 = 2131165213;
			
			// aapt resource value: 0x7f07000c
			public const int RegB = 2131165196;
			
			// aapt resource value: 0x7f07001f
			public const int RegBut = 2131165215;
			
			// aapt resource value: 0x7f07000f
			public const int Register = 2131165199;
			
			// aapt resource value: 0x7f070038
			public const int SAdd = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int SB1 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int SB2 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int SB3 = 2131165243;
			
			// aapt resource value: 0x7f070032
			public const int SYS = 2131165234;
			
			// aapt resource value: 0x7f070037
			public const int Star = 2131165239;
			
			// aapt resource value: 0x7f070031
			public const int StartY = 2131165233;
			
			// aapt resource value: 0x7f070024
			public const int TAdd = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int TB1 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int TB2 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int TB3 = 2131165224;
			
			// aapt resource value: 0x7f070023
			public const int Think = 2131165219;
			
			// aapt resource value: 0x7f070049
			public const int UsName = 2131165257;
			
			// aapt resource value: 0x7f070010
			public const int Username = 2131165200;
			
			// aapt resource value: 0x7f070048
			public const int Welcome = 2131165256;
			
			// aapt resource value: 0x7f07002c
			public const int checkBox1 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int checkBox2 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int checkBox3 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int checkBox4 = 2131165231;
			
			// aapt resource value: 0x7f070006
			public const int checkedTextView1 = 2131165190;
			
			// aapt resource value: 0x7f070013
			public const int checkedTextView2 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int checkedTextView3 = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int checkedTextView4 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int checkedTextView5 = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int checkedTextView6 = 2131165214;
			
			// aapt resource value: 0x7f07002b
			public const int gridLayout1 = 2131165227;
			
			// aapt resource value: 0x7f070009
			public const int imageView1 = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f070022
			public const int linearLayout4 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int linearLayout5 = 2131165221;
			
			// aapt resource value: 0x7f070029
			public const int linearLayout6 = 2131165225;
			
			// aapt resource value: 0x7f070036
			public const int linearLayout7 = 2131165238;
			
			// aapt resource value: 0x7f070045
			public const int ratingBar1 = 2131165253;
			
			// aapt resource value: 0x7f070008
			public const int scrollView1 = 2131165192;
			
			// aapt resource value: 0x7f07003c
			public const int scrollView4 = 2131165244;
			
			// aapt resource value: 0x7f070043
			public const int scrollView5 = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int scrollView6 = 2131165254;
			
			// aapt resource value: 0x7f070021
			public const int spinner1 = 2131165217;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070035
			public const int textView10 = 2131165237;
			
			// aapt resource value: 0x7f07003d
			public const int textView11 = 2131165245;
			
			// aapt resource value: 0x7f070044
			public const int textView12 = 2131165252;
			
			// aapt resource value: 0x7f070020
			public const int textView13 = 2131165216;
			
			// aapt resource value: 0x7f070014
			public const int textView2 = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int textView3 = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int textView4 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int textView5 = 2131165212;
			
			// aapt resource value: 0x7f07002a
			public const int textView6 = 2131165226;
			
			// aapt resource value: 0x7f070030
			public const int textView7 = 2131165232;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Register = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Search = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int UMain = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
